//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeoulStayS4.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SeoulStayS4Entities : DbContext
    {
        public SeoulStayS4Entities()
            : base("name=SeoulStayS4Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Amenities> Amenities { get; set; }
        public virtual DbSet<Areas> Areas { get; set; }
        public virtual DbSet<Attractions> Attractions { get; set; }
        public virtual DbSet<BookingDetails> BookingDetails { get; set; }
        public virtual DbSet<Bookings> Bookings { get; set; }
        public virtual DbSet<CancellationPolicies> CancellationPolicies { get; set; }
        public virtual DbSet<CancellationRefundFees> CancellationRefundFees { get; set; }
        public virtual DbSet<Coupons> Coupons { get; set; }
        public virtual DbSet<DimDates> DimDates { get; set; }
        public virtual DbSet<ItemAmenities> ItemAmenities { get; set; }
        public virtual DbSet<ItemAttractions> ItemAttractions { get; set; }
        public virtual DbSet<ItemPictures> ItemPictures { get; set; }
        public virtual DbSet<ItemPrices> ItemPrices { get; set; }
        public virtual DbSet<Items> Items { get; set; }
        public virtual DbSet<ItemScores> ItemScores { get; set; }
        public virtual DbSet<ItemTypes> ItemTypes { get; set; }
        public virtual DbSet<Scores> Scores { get; set; }
        public virtual DbSet<Transactions> Transactions { get; set; }
        public virtual DbSet<TransactionTypes> TransactionTypes { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UserTypes> UserTypes { get; set; }
    }
}
